FROM golang:alpine as build-env

ENV GO111MODULE=auto

RUN apk update && apk add bash ca-certificates git gcc g++ libc-dev

RUN mkdir /blog-server
RUN mkdir -p /blog-server/proto 

WORKDIR /blog-server

COPY ./proto/voting.pb.go /blog-server/proto
COPY ./server/main.go /blog-server
COPY ./database /blog-server/database
COPY ./services /blog-server/services
COPY ./models /blog-server/models

COPY go.mod .
COPY go.sum .

RUN go mod download

RUN go build -o blog-server .

CMD ./blog-server